# Generated by Django 5.0.3 on 2024-03-31 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='is_actice',
            new_name='is_active',
        ),
    ]
