# Generated by Django 5.0.3 on 2024-03-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_link',
            new_name='slug',
        ),
    ]
